CREATE TABLE [SALESMEN](
	[SALESMAN] [numeric](15, 0) IDENTITY(1,1) NOT NULL,
	[ORIGIN_FORM] [numeric](6, 0) NULL,
	[ORIGIN_MASTER_TABLE] [numeric](6, 0) NULL,
	[ORIGIN_MASTER_REGISTER] [numeric](15, 0) NULL,
	[INCLUSION_LOG_REGISTER] [numeric](15, 0) NULL,
	[NAME] [varchar](60) NOT NULL,
	[DEPARTMENT_CODE] [numeric](5, 0) NULL,
	[COMMISSION] [numeric](6, 2) NULL,
	[ENTITY] [numeric](15, 0) NOT NULL,
	[PDV_OPERATOR_CODE] [numeric](15, 0) NULL,
	[COMPANY_USING] [numeric](15, 0) NULL,
	[MAXIMUM_PMC_DISCOUNT] [numeric](15, 2) NULL,
	[TOTAL_COUNTER_DISCOUNT] [varchar](1) NULL,
	[SUPERVISOR] [varchar](1) NULL,
	[FP_USER] [varchar](15) NULL,
	[FP_PASSWORD] [varchar](15) NULL,
	[ACTIVE_REGISTRATION] [varchar](1) NULL,
	[GUID] [uniqueidentifier] NOT NULL,
	[DISCOUNT_POSITION] [numeric](15, 0) NULL,
	[COMMISSION_POSITION] [numeric](15, 0) NULL,
	[MOTOBOY_RATE] [numeric](15, 2) NULL,
	[MOTORCYCLIST] [varchar](1) NULL,
	[EMAIL] [varchar](120) NULL,
	[BIDDING] [varchar](1) NULL,
	[USER] [numeric](15, 0) NULL,
	[SALESMAN_EMAIL] [varchar](120) NULL,
	[POSITION_COMMISSION] [numeric](15, 0) NULL,
	[PHYSICAL_THERAPIST] [varchar](1) NULL,
	[COMMISSION_GROUP] [numeric](15, 0) NULL
) ON [PRIMARY]
GO
