 --1 -- CREATING NEW DB
CREATE DATABASE DB_COMMERCIAL

/* 2 -- LISTING TABLES FROM SOURCE

ENTIDADES                
ENDERECOS               
ESTADOS                       
CLASSIFICACOES_CLIENTES           
PRODUTOS           
FAMILIAS_PRODUTOS  
SECOES_PRODUTOS    
GRUPOS_PRODUTOS    
SUBGRUPOS_PRODUTOS 
MARCAS           
VENDEDORES
VENDAS_ANALITICAS
*/

sp_help CLASSIFICACOES_CLIENTES           


--3 -- Picking scripts and do translation
