--1 -- CREATING NEW DB
CREATE DATABASE DB_COMMERCIAL

/* 2 -- LISTING TABLES FROM SOURCE

ENTIDADES               
CLASSIFICACOES_CLIENTES 
ENDERECOS               
ESTADOS          
ENTIDADES               
CLASSIFICACOES_CLIENTES 
ENDERECOS               
ESTADOS          
PRODUTOS           
FAMILIAS_PRODUTOS  
SECOES_PRODUTOS    
GRUPOS_PRODUTOS    
SUBGRUPOS_PRODUTOS 
MARCAS           
VENDEDORES
VENDAS_ANALITICAS
*/
